Authentification/urls.py
from django.urls import path
from . import views

app_name='Authentification'

urlpatterns = [
    path('', views.Accueil, name='Accueil'),
    path('identification/',views.Identification,name='identification'),
    path('inscription/',views.Inscription,name='inscription'),
    path('logout/',views.Log_out,name='logout'),
]

E_vaccination/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Authentification.urls')),
    path('Services/',include('Services.urls')),
    path('Profil/',include('Profil.urls')),

    
]

Profil/urls.py
from django.urls import path
from . import views

app_name='Profil'

urlpatterns = [
    path('Profil/', views.Profil, name='Profil'),
    path('Infopers/',views.InfoPers,name='infopers'),
    path('Reclamation/',views.reclamation_view,name='reclamation'),
    path('telecharger-passe-vaccinal/', views.telecharger_passe_vaccinal, name='telecharger_passe_vaccinal'),
    path('AfficherReclamation/',views.afficher_reclamations,name='afficherReclamation'),
    
]

Profil/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


# Create your models here.


class EquipeMedicale(models.Model):
    numEquipe=models.IntegerField(primary_key=True)
    def __str__(self):
        return str(self.numEquipe)

class MembreEquipe(models.Model):
    nom=models.CharField(max_length=50)
    prenom=models.CharField(max_length=50)
    cin=models.CharField(max_length=10)
    equipe = models.ForeignKey(EquipeMedicale, on_delete=models.CASCADE ,null=True)
    def __str__(self):
        return self.nom
    


    
class Citoyen(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)
    date_naissance = models.DateField(default='2023-01-01')
    adresse = models.CharField(max_length=70)
    telephone = models.CharField(max_length=13,unique=True)
    cin = models.CharField(max_length=10,unique=True)
    date_vaccination1 = models.DateField(default='2023-01-01')
    date_vaccination2 = models.DateField(default='2023-01-01')
    equipe = models.ForeignKey(EquipeMedicale, on_delete=models.CASCADE, null=True)
    profil_complete = models.BooleanField(default=False)
    def __str__(self):
        return self.nom

    def get_telecharger_passe_vaccinal_url(self):
        return reverse('Profil:telecharger_passe_vaccinal')



class Reclamation(models.Model):
    # Champs pour les informations de la réclamation
    citoyen = models.ForeignKey(Citoyen, on_delete=models.CASCADE)
    nom = models.CharField(max_length=100,null=False)
    date_reclamation = models.DateTimeField(null=False)
    description = models.TextField(null=False)

    # Champs pour les informations sur les effets secondaires
    symptomes = models.TextField(null=False)
    date_effets_secondaires = models.DateField(null=False)

    # Champs supplémentaires pour le suivi de la réclamation
    est_traitee = models.BooleanField(default=False)
    date_traitement = models.DateTimeField(null=True, blank=True)
    commentaire_traitement = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"Réclamation de {self.nom} ({self.date_reclamation})"

Profil/forms.py
from django import forms
from .models import Citoyen,Reclamation
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class CitoyenForm(forms.ModelForm):
    def clean_date_naissance(self):
        date_naissance = self.cleaned_data['date_naissance']
        if date_naissance > timezone.now().date():
            raise forms.ValidationError("La date de naissance ne peut pas être supérieure à la date d'aujourd'hui.")
        return date_naissance
    class Meta:
        model=Citoyen
        fields=['date_naissance','adresse','telephone','cin']


class ReclamationForm(forms.ModelForm):
    class Meta:
        model = Reclamation
        fields = ['nom', 'date_reclamation', 'description', 'symptomes', 'date_effets_secondaires']

    

Profil/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from .forms import CitoyenForm,ReclamationForm
from .models import Citoyen,Reclamation
from django.contrib.auth.decorators import login_required
from reportlab.pdfgen import canvas
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save


# Create your views here.

@receiver(post_save, sender=User)
def create_citoyen(sender, instance, created, **kwargs):
    if created:
        Citoyen.objects.create(user=instance)

def Profil(request):
    user = request.user
    nom = user.first_name
    prenom = user.last_name

    # Vérifiez si l'utilisateur a un objet Citoyen associé
    citoyen = user.citoyen

    # Vérifiez si les champs pertinents de l'instance Citoyen sont vides
    if citoyen and not (citoyen.nom and citoyen.prenom and citoyen.date_naissance and citoyen.adresse and citoyen.telephone and citoyen.cin):
        show_remplir_info = True
    else:
        show_remplir_info = False

    return render(request, 'profil/profil.html', {'nom': nom, 'prenom': prenom, 'show_remplir_info': show_remplir_info})





from django.shortcuts import get_object_or_404

@login_required
def InfoPers(request):
    # Vérifier si l'utilisateur a déjà une instance de Citoyen associée
    citoyen = get_object_or_404(Citoyen, user=request.user)

    if request.method == 'POST':
        form = CitoyenForm(request.POST, instance=citoyen)
        if form.is_valid():
            person_info = form.save(commit=False)
            person_info.nom = request.user.first_name
            person_info.prenom = request.user.last_name
            person_info.save()

            return redirect('Profil:Profil')
    else:
        form = CitoyenForm(instance=citoyen)

    return render(request, 'profil/infoPerso.html', {'form': form})



def reclamation_view(request):
    if request.method == 'POST':
        form = ReclamationForm(request.POST)
        if form.is_valid():
            reclamation = form.save(commit=False)
            citoyen = get_object_or_404(Citoyen, user=request.user)
            reclamation.citoyen = citoyen
            reclamation.save()
            return redirect('Profil:Profil')
    else:
        form = ReclamationForm()

    context = {
        'form': form
    }

    return render(request, 'profil/reclamation.html', context)



def afficher_reclamations(request):
    user = request.user
    reclamations = Reclamation.objects.filter(citoyen=user.citoyen)

    return render(request, 'profil/afficherReclamation.html', {'reclamations': reclamations})


def telecharger_passe_vaccinal(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="passe_vaccinal.pdf"'

    p = canvas.Canvas(response)

    citoyen = request.user.citoyen

    # Définir les coordonnées de départ en bas de la page
    y = 800

    # Ajouter les informations spécifiques du citoyen dans le passe vaccinal
    p.drawString(100, y, f"Nom: {citoyen.nom}")
    y -= 20
    p.drawString(100, y, f"Prénom: {citoyen.prenom}")
    y -= 20
    p.drawString(100, y, f"Date de naissance: {citoyen.date_naissance}")
    y -= 20
    p.drawString(100, y, f"Adresse: {citoyen.adresse}")
    y -= 20
    p.drawString(100, y, f"Téléphone: {citoyen.telephone}")
    y -= 20
    p.drawString(100, y, f"CIN: {citoyen.cin}")
    y -= 20
    p.drawString(100, y, f"Date vaccination 1: {citoyen.date_vaccination1}")
    y -= 20
    p.drawString(100, y, f"Date vaccination 2: {citoyen.date_vaccination2}")

    p.showPage()
    p.save()

    return response

templates/profil/afficherReclamation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1 class="titrereclam">Mes réclamations</h1>
    <ul>
        {% for reclamation in reclamations %}
            <li>{{ reclamation }}</li>
        {% empty %}
            <li>Aucune réclamation trouvée.</li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/profil/infoPerso.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form id="infopers" method="POST"  action="{% url 'Profil:infopers' %}">
    {% csrf_token %}
    <div class="mb-4">
        {% if form.date_naissance.errors %}
      <div class="alert alert-danger" role="alert" data-mdb-color="danger">
        {{ form.date_naissance.errors }}
      </div>  
      {% endif %}
        
       <div class="form-group {% if form.date_naissance.errors %}has-error{% endif %}">
          <label for="{{ form.date_naissance.id_for_label }}">Date de naissance :</label>
              {{ form.date_naissance }}
       
  </div>
    </div>
    <div class="mb-4">
        <label class="form-label" for="{{ form.nom.id_for_label }}">Adresse</label>
        {{ form.adresse}}
    </div>
    <div class="mb-4">
        <label class="form-label" for="{{ form.nom.id_for_label }}">Telephone</label>
         {{ form.telephone}}
    </div>
    <div class="mb-4">
        <label class="form-label" for="{{ form.nom.id_for_label }}">CIN</label>
         {{ form.cin}}
    </div>
    
    <div class="mb-4">
        <button id="btnsub" type="submit" class="btn btn-primary">Soumettre</button>
    </div>
    
</form>
{% endblock content %}

templates/profil/profil.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



    {% if show_remplir_info %}
    <h4 class="alrt">Veuillez avant tout remplir les informations demandées dans le formulaire afin de finaliser votre inscription</h4>
        <div class="btnremplirInfo">
            <a href="{% url 'Profil:infopers' %}" class="btn btn-primary">
                Remplir mes informations
            </a>
        </div>
    {% endif %}
<div class="nometprenom">
    <h1 class="nom">Nom: {{ nom }}</h1>
    <h1 class="prenom">Prénom: {{ prenom }}</h1>
</div>
    

    <div class="row" id="cards">
        <div class="col-sm-4">
            <div class="card" style="width: 12rem;">
                <img src="{% static 'images/profil/reclam.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a href="{% url 'Profil:telecharger_passe_vaccinal' %}" class="btn btn-primary">
                        Télécharger Passe Vaccinal
                    </a>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="card" style="width: 12rem;">
                <img src="{% static 'images/profil/document.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a href="{% url 'Profil:reclamation' %}" class="btn btn-primary">
                        Faire une réclamation
                    </a>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="card" style="width: 12rem;">
                <img src="{% static 'images/profil/document-texte.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a href="{% url 'Profil:afficherReclamation' %}" class="btn btn-primary">
                        Voir mes réclamations
                    </a>
                </div>
            </div>
        </div>
    </div>
    
    <div class="btndeco">
        <a href="{% url 'Authentification:logout' %}" class="btn btn-danger">
            <i class="fa fa-sign-out"></i> Déconnexion
        </a>
    </div>
    
    
{% endblock content %}

templates/profil/reclamation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<form class="reclamation" method="POST" action="{% url 'Profil:reclamation' %}">
    {% csrf_token %}
    
    
    <div class="mb-4">
      <label class="form-label " for="{{ form.nomRec.id_for_label }}">titre</label>
      {{ form.nom }}
    </div>
    
    
    <div class="mb-4">
      <label class="form-label " for="{{ form.date_reclamation.id_for_label }}">Date de réclamation :</label>
      {{ form.date_reclamation }}
    </div>
    
    
    <div class="mb-4">
      <label class="form-label " for="{{ form.description.id_for_label }}">Description :</label>
      {{ form.description }}
    </div>
    
    
    <div class="mb-4">
      <label class="form-label " for="{{ form.symptomes.id_for_label }}">Symptômes :</label>
      {{ form.symptomes }}
    </div>
    
    
    <div class="mb-4">
      <label class="form-label " for="{{ form.date_effets_secondaires.id_for_label }}">Date des effets secondaires :</label>
      {{ form.date_effets_secondaires }}
    </div>
    
    
    <div class="mb-4">
      <button id="btnsub" type="submit" class="btn btn-primary">Envoyer</button>
  </div>
  </form>
{% endblock content %}  