Authentification/urls.py
from django.urls import path
from . import views

app_name='Authentification'

urlpatterns = [
    path('', views.Accueil, name='Accueil'),
    path('identification/',views.Identification,name='identification'),
    path('inscription/',views.Inscription,name='inscription'),
    path('logout/',views.Log_out,name='logout'),
]

E_vaccination/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Authentification.urls')),
    path('Services/',include('Services.urls')),
    path('Profil/',include('Profil.urls')),

    
]

Profil/urls.py
from django.urls import path
from . import views

app_name='Profil'

urlpatterns = [
    path('Profil/', views.Profil, name='Profil'),
    path('Infopers/',views.InfoPers,name='infopers'),
    path('Reclamation/',views.reclamation_view,name='reclamation'),
    path('telecharger-passe-vaccinal/', views.telecharger_passe_vaccinal, name='telecharger_passe_vaccinal'),
    path('AfficherReclamation/',views.afficher_reclamations,name='afficherReclamation'),
    
]

Authentification/models.py
from django.db import models




    

    

Authentification/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.db.models import Q
from django.contrib import messages

# Create your views here.

def Accueil(request):
    return render(request,'index.html',{}) 


def Identification(request):
    if request.method == 'POST':
        email = request.POST.get('email', None)
        password = request.POST.get('password', None)

        user = User.objects.filter(email=email).first()
        if user:
            auth_user = authenticate(username=user.username, password=password)
            if auth_user:
                login(request, auth_user)
                request.session['is_authenticated'] = True  # Définir la variable de session
                return redirect('Profil:Profil')
            else:
                messages.error(request, "Mot de passe incorrect.")
        else:
            messages.error(request, "Email invalide.")

    # Vérifier si l'utilisateur est déjà authentifié et rediriger vers le profil
    if request.user.is_authenticated or request.session.get('is_authenticated', False):
        return redirect('Profil:Profil')

    return render(request, 'authentification/identification.html', {})


def Inscription(request):
    error=False
    message=''
    if request.method=='POST':
        nom=request.POST.get('nom',None)
        prenom=request.POST.get('prenom',None)
        email=request.POST.get('email',None)
        password1=request.POST.get('password1',None)
        password2=request.POST.get('password2',None)

        try:
            validate_email(email)
        except:
            error=True
            message="Veuillez saisir un email valid !"

        if error==False:
            if password1!=password2:
                error=True
                message="Les mots de passe ne correspondent pas ! "
        
        user=User.objects.filter(Q(email=email)).first()
        if user:
            error=True
            message="un utilisateur avec l'email {email} existe deja !"

        if error==False:
            user=User(
                first_name=prenom,
                last_name=nom,
                email=email,
                username=prenom
            )
            user.save()
            user.password=password1
            user.set_password(user.password)
            user.save()
            return redirect('Authentification:identification')
    context={
        'error':error,
        'message':message
    }
    return render(request,'authentification/inscription.html',context)

def Log_out(request):
    logout(request)
    return redirect('Authentification:identification')

templates/authentification/identification.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form id="identification" method="POST" class="border-class">
  {% csrf_token %}
 
  {% if messages %}
  <ul class="errorlist">
    {% for message in messages %}
    <div class="alert alert-danger" role="alert" data-mdb-color="danger">
      {{ message }}
      </div>
    {% endfor %}
  </ul>
{% endif %}
    <div class="mb-3">
      <label  class="form-label">Email</label>
      <input type="email" class="form-control" name="email"/>
    </div>
    <div class="mb-3">
      <label  class="form-label">Mot de passe</label>
      <input type="password" class="form-control" name="password"/>
    </div>
    <div>
      <a class="lien" href="{% url 'Authentification:inscription' %}">créer un compte</a>
    </div>
    
    <button id="btnsub" type="submit" class="btn btn-primary">Connexion</button>

</form>

{% endblock content %}

templates/authentification/inscription.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form id="inscription" method="POST" action="{% url 'Authentification:inscription' %}" class="row g-3 needs-validation" novalidate>
  {% csrf_token %}
  <div class="col-md-4">
    <label for="{{ form.nom.id_for_label }}" class="form-label">Nom</label>
    <input type="text" class="form-control" name="nom"/>
  </div>
  <div class="col-md-4">
    <label for="{{ form.prenom.id_for_label }}" class="form-label">Prenom</label>
    <input type="text" class="form-control" name="prenom"/>
  </div>
  <div class="col-md-4">
    <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
    <input type="text" class="form-control" name="email"/>
  </div>
  <div class="col-md-12">
    <label for="{{ form.mot_de_passe.id_for_label }}" class="form-label">Mot de passe</label>
    <input type="password" class="form-control" name="password1"/>
  </div>
  <div class="col-md-12">
    <label for="{{ form.mot_de_passe.id_for_label }}" class="form-label">resaisir le mot de passe</label>
    <input type="password" class="form-control" name="password2"/> 
  </div>
  
  <div class="col-12">
    <button class="btn btn-primary" type="submit">S'inscrire</button>
  </div>
  {% if error %}
  <div class="alert alert-danger" role="alert" data-mdb-color="danger">
    {{message}}
  </div>
  {% endif %}
</form>

{% endblock content %}