Authentification/urls.py
from django.urls import path
from . import views

app_name='Authentification'

urlpatterns = [
    path('', views.Accueil, name='Accueil'),
    path('identification/',views.Identification,name='identification'),
    path('inscription/',views.Inscription,name='inscription'),
    path('logout/',views.Log_out,name='logout'),
]

E_vaccination/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Authentification.urls')),
    path('Services/',include('Services.urls')),
    path('Profil/',include('Profil.urls')),

    
]

Profil/urls.py
from django.urls import path
from . import views

app_name='Profil'

urlpatterns = [
    path('Profil/', views.Profil, name='Profil'),
    path('Infopers/',views.InfoPers,name='infopers'),
    path('Reclamation/',views.reclamation_view,name='reclamation'),
    path('telecharger-passe-vaccinal/', views.telecharger_passe_vaccinal, name='telecharger_passe_vaccinal'),
    path('AfficherReclamation/',views.afficher_reclamations,name='afficherReclamation'),
    
]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'css/homeStyle.css' %}"> 
    <link rel="stylesheet"  href="{% static 'css/informations.css' %}"> 
    <link rel="stylesheet"  href="{% static 'css/mapLocalisation.css' %}">
    <link rel="stylesheet"  href="{% static 'css/authentification.css' %}">
    <link rel="stylesheet"  href="{% static 'css/infoper.css' %}">
    <link rel="stylesheet"  href="{% static 'css/profil.css' %}">
    <link rel="stylesheet"  href="{% static 'css/reclamation.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/accueil/logo.png' %}">
    <title>VaxEase</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'Authentification:Accueil' %}"></a>
      <img src="{% static 'images/accueil/logo.png' %}" alt="" width="60" height="50">
    </a>
      <a class="navbar-brand" style="color: rgb(65, 118, 65);font-size: 30px; font-weight: bold;" href="{% url 'Authentification:Accueil' %}">VaxEase</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="font-weight: bold; font-size:20px">
          <li class="nav-item">
            <a class="nav-link active" id="accueil" style="color: rgb(8, 8, 129);" aria-current="page" href="{% url 'Authentification:Accueil' %}">Accueil</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link " id="information" style="color: rgb(8, 8, 129);" href="{% url 'Informations' %}" role="button"  aria-expanded="false">
              Informations sur le vaccin
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="compte" style="color: rgb(8, 8, 129);" href="{% url 'map' %}">Map de localisation</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="compte" style="color: rgb(8, 8, 129);" href="{% url 'Authentification:identification' %}">Mon Profil</a>
          </li>
        </ul>
        <button class="btn btn-outline-success" ><a href="{% url 'Authentification:identification' %} " style="text-decoration: none; font-weight: bold; color:rgb(8, 8, 129)">S'identifier</a></button>
      </div>
    </div>
  </nav>
</header>

          
     
<body>
  {% block content %} {% endblock %}
  <script src="{% static 'js/souligner.js' %}"></script>
  
 
</body>
<footer>
  <div class="card text-center">
    
    <div class="card-body">
      <h5  id="foot" class="card-title">Me protéger, protéger mon pays! </h5>
      <a href="https://www.sante.gov.ma/Pages/Accueil.aspx" class="btn btn-primary">Ministère de la santé</a>
    </div>
    
  </div>
</footer>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="row container">
    <div class="col-md-7">
        <img id=img2 class="img-fluid rounded mx-auto d-block" src="{% static 'images/accueil/img2.jpg' %}" alt="">
    </div>
    <div class="col-md-5 container">
        <h1 class="vax">VaxEase :</h1>
        <h1 class="title">vaccination contre le coronavirus</h1>
    </div>
</div>

<h1 class="operationvax">Opération de vaccination</h1>
<div class="row container">
    <div class="col-md-6">
        <h3 class="lieudevax">LIEUX DE VACCINATION</h3>
        <img id="lieuvax" class="img-fluid rounded mx-auto d-block" src="{% static 'images/accueil/LIE.png' %}" alt="">
    </div>
    <div class="col-md-6">
        <h3 class="aspect">ASPECT PRATIQUE DE LA VACCINATION ANTICOVID : CIRCUIT DU FUTUR VACCINE</h3>
        <img id="aspectimg" class="img-fluid rounded mx-auto d-block" src="{% static 'images/accueil/AS.png' %}" alt="">
    </div>
</div>

<h1 class="video">Vidéothèque</h1>
<div class="row container" >
    <div class="col-md-6">
        <iframe class="video1" width="560" height="315" src="https://www.youtube.com/embed/zaGqmAVnEbE" frameborder="0" allowfullscreen></iframe>
    </div>
    <div class="col-md-6">
        <iframe  class="video2" width="560" height="315" src="https://www.youtube.com/embed/HkRYSK-MNuw" frameborder="0" allowfullscreen></iframe>
    </div>
    
</div>

{% endblock content %}